### ISSUE TITLE
Does the API support push style linting?

### ISSUE THREAD

**Issue by devoncarew** [AtomLinter/linter-plus#10]
By push style, I mean supports for linters for languages with non-local changes. So a change in file A might need to update the errors and warnings for file A and B. Currently it looks like the linter only asks for lints for A and there's no easy way to update the ones for B (which might also be open).

**Comment by steelbrain** [comment]
We have a file attribute in the error shape, have a look at https://github.com/AtomLinter/linter-plus/blob/steelbrain/feature-error-objects/README.md#error-object-shapes
This way a linter from file A can report errors in file B

**Comment by devoncarew** [comment]
Will this append lints to the other file (B)? Replace all lints for that other file? Can I clear out existing lints for it, if a change in file A fixes an issue infile B?

**Comment by steelbrain** [comment]
The current design shows all known errors for all files, and they have a button which, when clicked takes the user to that error location. Here's how it looks ![Screenshot](https://cloud.githubusercontent.com/assets/4278113/7841067/266c448a-044f-11e5-957a-b3d99cc11701.png)

**Comment by steelbrain** [comment]
Please note that those error messages are bound to the text editor, you will see messages for all files that it's linters tells us, error messages from another texteditor will only be shown when it's selected.

**Comment by radicaled** [comment]
To expand a bit on what @devoncarew is getting at, the way our linting process works is that we integrate with an external process that is always running. The process sends us messages over STDIN, updating us on the status of files in our project.

So, consider this situation:

Let's say a user opens a freshly checked out project, but they haven't yet acquired all the necessary dependencies (via `pub get`, which is analogous to `npm install`). Our external process detects this, and spews out many errors about how some file references are invalid, etc.

So the user goes to the console and runs `pub get`. They now have all the dependencies required. Our external service sees this, and is now happy, and reports that all is well. But we haven't touched any of the files in Atom yet, so `linter-plus` hasn't called our linter integration.

Using `linter-plus`, how would we be able to say, "all the files are OK now?" or "these files have changed" without having to wait for the user to type something in one of the editors?

It'd be great if we could get a `Linter`-type and call `addWarning`, `addError`, etc.

**Comment by steelbrain** [comment]
That is exactly what I had proposed in the gitter room yesterday, though I didn't feel the need of it before launch. But It can surely make it into the first launch.
In the move, we're gonna split the linter into two types of linters, Project Based and File Based, Both will have almost the same API. I am sure You're going to enjoy it.

**Comment by radicaled** [comment]
That sounds excellent. I'll watch this repo with great expectations. :)

**Comment by steelbrain** [comment]
Just ignore what I said above, I had mis-understood your question. You don't have to wait for anything, It's already implemented in the master branch. All you have to do is consume the `linter-plus-self` service instead of `linter-plus` and You will get the main linter class, You will then be able to manipulate all of the editor linters and will be able to lint when you please.
