### ISSUE TITLE
Is this package taking over for `linter`?

### ISSUE THREAD

**Issue by devoncarew** [AtomLinter/linter-plus#11]
It doesn't look like it's published yet. Is it the intention for this package to replace `linter`? Is there an ETA, and can the two linting packages co-exist? Thanks for the info!

**Comment by steelbrain** [comment]
Yep, it's gonna replace AtomLinter. and all of the linters are gonna be updated to support this new API.

**Comment by steelbrain** [comment]
My current target is to make it production ready before 1st of next month. Transitioning the linters however is a time-taking task.
