### ISSUE TITLE
separate panels for current file and project wide offenses

### ISSUE THREAD

**Issue by hd-deman** [AtomLinter/linter-plus#15]
![sketch](http://hd-deman-stuff.s3.amazonaws.com/Bez_imeni-1__100_other_native_labels_RGB8__2015-05-29_03-40-20.png)

**Comment by steelbrain** [comment]
What do you indent to put on the other native labels side?

**Comment by hd-deman** [comment]
![](http://hd-deman-stuff.s3.amazonaws.com/linter-rubocop.coffee_-_UsersdemanprojectsAtomLinter_-_Atom_2015-05-29_03-46-08.png)
so that help us to save some space
