### ISSUE TITLE
What is a Trace? 

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#16]

**Comment by steelbrain** [comment]
Trace is an object that you add in Error or Warning and it'll be shown in the inline tooltip. It's quite helpful for project-based languages like flow and hack.

**Comment by AsaAyers** [comment]
Does it have a shape? What is its purpose? The Readme seems to indicate it's required. What if I don't use flow or hack and I still don't know what a Trace is?

**Comment by steelbrain** [comment]
It's not required, You can provide an empty array if you want.
