### ISSUE TITLE
view is not updated

### ISSUE THREAD

**Issue by iam4x** [AtomLinter/linter-plus#18]
Status bar view should be updated but it won't in these cases:

- when last file is closed of the editor is closed, you will still have the linter error in the status bar and messages bubble
![screen shot 2015-05-31 at 18 39 11](https://cloud.githubusercontent.com/assets/893837/7902775/62b69098-07c5-11e5-9c9b-d42ff3183686.png)

- when you switch to a file which is not processed by any linter
![gif](http://g.recordit.co/4NpWc87vIO.gif)

**Comment by steelbrain** [comment]
@iam4x That case when there's no active editor, we choose to avoid any linting. We should empty the panel however, the second case looks like a bug though.

**Comment by iam4x** [comment]
@steelbrain I'm already on it :+1: 

I think it's in `linter-view.coffee` on render we should dispose already existing views on line 6 - 7

**Comment by steelbrain** [comment]
Yep. The first case is in the range you tell. The second case I am not sure

**Comment by iam4x** [comment]
I have an idea for it, just reporting. I'll drop a PR, cleaning some stuff about the view.

**Comment by steelbrain** [comment]
Man, It's been two hours, no update :stuck_out_tongue:

**Comment by iam4x** [comment]
Just pulled your work, not linting anymore. 

I did some work on it too, you can check https://github.com/AtomLinter/linter-plus/commit/41c0f9595c35f6acd01ff2490cbb42189934c357
