### ISSUE TITLE
Publish on APM

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-plus#24]
Please close this when linter-plus is published on APM.
Only using this issue as a trigger for pull requests updating linters to the latest API.

**Comment by hd-deman** [comment]
We don't wan't to publish it. instead of this we gonna replace master branch in linter package.

**Comment by k2b6s9j** [comment]
For the purpose of other packages this the same. As long as we can have an issue that triggers developers when linter-plus hits main stream avalibility.

**Comment by steelbrain** [comment]
I have published it as `linter-plus` for now, because I couldn't wait for the compatibility and stuff and wanted to publish the new version of my packages.
So Yeah, It'll be renamed to `linter`, but until then it's linter-plus.

**Comment by AsaAyers** [comment]
The code for compatibility is already in `master` but if you install it with the name `linter-plus` none of it will work. It's not backward compatible.

**Comment by steelbrain** [comment]
I am happy to rename it to `linter`, all I need is a green signal from You @AsaAyers, @k2b6s9j @park9140 @hd-deman @iam4x

**Comment by AsaAyers** [comment]
You've got the :+1: from me.

I've only been trying to make sure the quality is good enough that you won't get a flood of issues when it releases, but it's not worth the effort at this time.

**Comment by k2b6s9j** [comment]
Been using nothing but this for my coding for a while now. :+1:

**Comment by park9140** [comment]
Seems fine to me :+1:

**Comment by AsaAyers** [comment]
This has been published at `linter@1.0.x`
