### ISSUE TITLE
Support "Info" message type?

### ISSUE THREAD

**Issue by radicaled** [AtomLinter/linter-plus#28]
Looking at https://github.com/AtomLinter/linter-plus/wiki/Linter-API only two message types are supported: `Error`, and `Warning`. What about `Info`? Some linters return "Info" for stuff like "unused variable" or "unused method," etc.

**Comment by k2b6s9j** [comment]
If i recall correctly this API actually allows you to create your own message types.

**Comment by steelbrain** [comment]
You might want to have a look at https://github.com/AtomLinter/linter-plus/wiki/Styling-Messages
