### ISSUE TITLE
Transition Plan

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#29]
`linter-plus` is a rewrite that is going to replace `linter`. @steelbrain did the heavy lifting getting the linter rewritten and now we're near being able to publish it. Most of the discussion has happened or is happening on [gitter](https://gitter.im/AtomLinter/Linter).

What we know
===========

* The code for `linter-plus` will be published at https://atom.io/packages/linter and its internal name will be changed back to `linter`
* There will be a compatibility layer so that the new linter works with all of the existing plugins. #21
  * This layer will go away in a few weeks once every project has had time to switch to the new API

With this plan all users can update smoothly through the existing update process built into Atom. From their perspective it just looks like a redesigned UI.

We're still working out:
================

* What about the repositories?
  * Option 1
    * rename `AtomLinter/Linter#master` to `master-old`
    * commit `AtomLinter/linter-plus/#master` as the new master in the `AtomLinter/Linter` repo.
    * con: This mixes the issues for the new and old linters. Cleanup needs to be done
  * Option 2
    * Move `AtomLinter/Linter` to a new name like `AtomLinter/Linter-old`
    * Move `AtomLinter/linter-plus` to `AtomLinter/Linter`
    * con: I don't know if this is possible. Github forwards requests to the new name when you move a repo, does that prevent you from moving a repo to the old name?

**Comment by k2b6s9j** [comment]
Option 2: A rename like that is allowed.

**Comment by iam4x** [comment]
Thank's @AsaAyers for the effort, I would go for option 1. (pros: keep stars, and we know that the redirection won't be an issue)

If we go for first solution, I'll help for cleaning :+1:

**Comment by steelbrain** [comment]
Option 2: 'cause we don't need all the open issues and stuff, It would give us a clean history, and we will still be able to publish it as linter by just making sure that the new version is +1 from the previous.
The only cons that I can think of is that we'll lose the stars, we won't lose the APM Stars or Downloads.
The Node Organization did the same recently, they moved io.js to https://github.com/nodejs/io.js and put the new version in https://github.com/nodejs/node
They did lose GitHub Stars, but it was worth that clean start.

**Comment by hd-deman** [comment]
Why not to start working on `linter` repo?

**Comment by steelbrain** [comment]
Because it has a hell lot of issues that are irrelevant to linter-plus.
Even now there are new PRs coming in.

**Comment by steelbrain** [comment]
Be advised everyone who has subscribed to the bug, We have replaced the old linter package with the new one. Make sure to upgrade to the latest API, 'cause the legacy code is temporary.

**Comment by basarat** [comment]
Looking at the docs : https://github.com/AtomLinter/Linter/wiki/Linter-API they seem out of date (e.g. is it `message` or `text`?). 

Any linters updated to the latest?

**Comment by basarat** [comment]
I have it working. Thanks for all the hard work and a simple clean API :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/8324574/55219170-1a95-11e5-89d9-49c840941054.png)

### Feature request in the update

Miss the label `TypeScript` against the error (previously done through the `linter` key) to tell the source of the error provider. But its a minor thing :rose:

**Comment by iam4x** [comment]
@basarat I agree with you, we should tell which linter is displaying the errors. (For instance when you have two linters working together)

**Comment by AsaAyers** [comment]
That's actually impossible to do at this point. We had talked about making the name of the linter a required part of the provider, but it didn't happen for 1.0.0.

**Comment by steelbrain** [comment]
You can, always, prepend your linter name to every error if you really want that feature back :smiley:

**Comment by basarat** [comment]
@steelbrain good idea. I've done that with my last push
![image](https://cloud.githubusercontent.com/assets/874898/8344050/5769c54e-1b1f-11e5-820f-141b42f1bf47.png)

**Comment by steelbrain** [comment]
Closing as the linter has been published so it doesn't make any sense to keep this open.
