### ISSUE TITLE
Ability to lint no matter the scope.

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-plus#32]
Or rather, being able to create a linter that is able to be called no matter what scope the file loaded is.

This would be incredibly helpful for linters like linter-flint, and linter-gradle, that are generic directory based build tools.

**Comment by steelbrain** [comment]
You mean like a `*` scope?

**Comment by k2b6s9j** [comment]
Yes. That would work well.

**Comment by steelbrain** [comment]
:+1: for that feature, if someone wants to implement it, it should be in the lint function of editor-linter
