### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by josa42** [AtomLinter/linter-plus#45]
Currently the linter (linter-plus) wont load because the version is 0.3.0 and Atom considers linter <=0.11.1 as deprecated.

![image](https://cloud.githubusercontent.com/assets/423234/8069384/6ec1e43c-0efa-11e5-94e1-36cee7723e62.png)

See: [atom/atom : deprecated-packages.json](https://github.com/atom/atom/blob/master/build/deprecated-packages.json#L898)

**Comment by AsaAyers** [comment]
How exactly are you trying to load it? Since it hasn't been released yet I checkout `master` and use `apm link`

**Comment by AsaAyers** [comment]
Nevermind, since I'm running Linux I don't get auto-updates from atom. 0.204 doesn't have this problem

**Comment by josa42** [comment]
Ya, I think it is that way since 0.206.0

> Atom now ships with the 1.0 API enabled and no longer loads packages that use deprecated APIs. You can run Atom with --include-deprecated-apis to still load them but the APIs will be completely removed in the upcoming 1.0 release.
