### ISSUE TITLE
Atom Core

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-plus#47]
## The Original Issue Text from AtomLinterPlus/linter-plus#1
An idea occurred to me on my way home today. Maybe the linter core should be made part of Atom core, much like AutoComplete. But I'd love to hear ideas from everyone involved.

[redacted cc]

Here's my thought process. Knowing where issues in your code/project exists is essential to coding, therefore it should be an essential part of the editor itself. This allows us to continue making linter providers/independent linters and optimize for their specific environments. This will also encourage a larger community if the core linter is part of the core.

Again, I could be totally out of line in this but, given the recent drama I thought it might be possible that the community and use cases of AtomLinter have grown too large for it's own independent organization and community and should be made a core part of the Atom community, especially given how many Atom users are dependent on AtomLinter and it's linters.

## An Image Archive of the Original Issue
![image](https://cloud.githubusercontent.com/assets/594124/8075707/b7272f2e-0f00-11e5-8d81-ff151c4d3f94.png)

## Everyone who took part in the conversation.
@k2b6s9j
@steelbrain 
@david-driscoll 
@AsaAyers
@lierdakil
@ctolkien

### Original CC
@AsaAyers (AtomLinter)
@hd-deman (AtomLinter)
@iam4x (AtomLinter)
@steelbrain (AtomLinter)
@kevinsawicki (Atom)
@dmnd (AtomLinter)
@maxbrunsfeld (Atom)
### OmniSharp
@david-driscoll
@nosami
@ctolkien
@Mpdreamz
@sgwill
### atom-lint
@yujinakayama
### atom-typescript
@basarat
### atom-haskell
@lierdakil
@chaika2013
### linter-hlint
@mdgriffith

**Comment by k2b6s9j** [comment]
And of course, we must include the fantastic @joefitzgerald of autocomplete-plus and go-plus, who dropped in our Gitter today to discuss this.

**Comment by steelbrain** [comment]
Moved the discussion to https://github.com/atom/atom/issues/7353
