### ISSUE TITLE
Invalid Linter Provided message isn't useful enough

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#60]
1. this doesn't stay long enough to read the details
2. it doesn't give any indication of what is wrong with the linter.

![selection_093](https://cloud.githubusercontent.com/assets/324999/8189359/ced5e380-1429-11e5-917f-4882f855cd04.png)

**Comment by steelbrain** [comment]
What ideas do you have?
Trace is not really useful here.

**Comment by AsaAyers** [comment]
I'll have a solution in a few minutes. I'm just opening the issue first.

**Comment by steelbrain** [comment]
Awesome
