### ISSUE TITLE
InvalidCharacterError when passing type.

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-plus#64]
Clang has a 'critical error' message type. When I pass this to the base linter package it throws an Exception saying it has a critical error. I realize that the space in the type is the issue here, but I was kinda hoping that the base linter package could replace unfriendly characters with friendly characters.

**Comment by steelbrain** [comment]
Yep, that's because when we add the classes, they DOM expects them not to contain spaces, maybe we could replace spaces with dashes when applying classes.

**Comment by iam4x** [comment]
@steelbrain I'm good with it, let's add dashes.

**Comment by steelbrain** [comment]
Just opened a PR for that.

**Comment by AsaAyers** [comment]
IMO we shouldn't add dashes. Since you insist that the linters should pass back arbitrary types and then style them the class name needs to be predictable and well documented. Are spaces dashes? underscores? just removed? No one needs to think about this. We should simply forbid spaces.

**Comment by steelbrain** [comment]
@AsaAyers that behavior is documented in the docs. and having spaces seems like a feature with no probs to me. I am open to ideas however.
