### ISSUE TITLE
Message bubbles should accept html instead of plain text

### ISSUE THREAD

**Issue by mostafaeweda** [AtomLinter/linter-plus#7]
I have a use case for the linter, where I want to provide a clickable url, with custom action in the error message to navigate to some location.

It would be helpful if the message bubble in the inline-view could support html.

/cc @bolinfest @Eschon

**Comment by steelbrain** [comment]
@mostafaeweda I completely understand why would you want to put html instead a bubble, but I think for the Nuclide IDE, you might want to use our Trace Feature, You can add Trace to any Error or Warning.
https://github.com/steelbrain/Atom-Hack/blob/rewrite/lib/atom-hack.coffee#L30

**Comment by mostafaeweda** [comment]
Oh, I think I'll love it :+1:  - but having complete control via HTML would also be nice to have

**Comment by mostafaeweda** [comment]
@steelbrain In general, how ready and complete is this rewrite to replace Atom linter and build on top of?

**Comment by steelbrain** [comment]
It is 100% working for my own personal linters, but you might have to wait until #6 is done. 'cause maybe we'll be renaming the service from `linter.plus` to `linter-plus`. and even if we do, that's all that you will have to change on your linter side.

**Comment by steelbrain** [comment]
@mostafaeweda Do you have an API in mind for this? Because if we will treat all bubble strings as html by default then it would create problems when we'll have html tags in messages.

**Comment by steelbrain** [comment]
Fixed by #9
