### ISSUE TITLE
Project seems to only track the current file

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#72]
I'm just going back and forth between these two tabs.

![selection_103](https://cloud.githubusercontent.com/assets/324999/8242977/30e4c114-15e1-11e5-8890-66dc47528d5f.png)
![selection_104](https://cloud.githubusercontent.com/assets/324999/8242978/329ccdf8-15e1-11e5-8bfc-95d881fd1f43.png)

**Comment by AsaAyers** [comment]
I don't think `Project` is a good name for that tab. Since we pass `Editor`s to the linter you can't actually lint the whole project unless we open every file in the project. `All Tabs` would be better representative of what it's supposed to do.

**Comment by steelbrain** [comment]
It's quite useful for me in atom-hack, and will also be useful for coffeelint. But I get your point, we should save the errors if the scope is file and count em all.

**Comment by AsaAyers** [comment]
How is having two tabs that only show the same thing useful? I really don't
get it. What am I missing here?

**Comment by steelbrain** [comment]
They don't show the same thing. The Current File tab only shows stuff that has `filePath` of the current file, and the other tab shows all the messages.
It needs a few tweaks to include messages from all linters to show in the project tab. So when a user opens one coffee file, he is able to know the errors in others as well.
It's **extremely** important for FlowJS and Hack and other project-based languages.
