### ISSUE TITLE
Allow neither tab to be selected

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#75]
![selection_107](https://cloud.githubusercontent.com/assets/324999/8264291/54a107c6-16b2-11e5-8fc8-0e9688fd4483.png)

This came up as a discussion in [gitter](https://gitter.im/AtomLinter/Linter) with @ababol.

**Comment by steelbrain** [comment]
:-1: for that feature. Any reasons on why would someone want to do that?

**Comment by AsaAyers** [comment]
I didn't think it seemed useful at first either, but then I remembered all the times I'm trying to read 3rd party code that uses a vastly different style from my own. I don't need the screen cluttered just because I don't agree with the coding style.

**Comment by AsaAyers** [comment]
> Also, how would the bottom status icon know which position you were last on, as everytime you save something, it removes the last messages and pushes new ones.

It should move relative to your cursor.

**Comment by ababol** [comment]
@steelbrain 
```
The max-height thing for the linter-panel is great but it's not enough.
...
Sometimes you just want to be focused to debug the old code and you don't want to have any visual distraction.
...
But what I mean is that if you are working on an old deprecated code, or on a minify code or anything like that, you don't want to have the linter-panel visible```

**Comment by steelbrain** [comment]
I am definitely :+1: on allowing the user to hide the panel.

**Comment by AsaAyers** [comment]
Lets say you're trying to clean up a project that has a TON of warnings/errors. It might look like this:

![](https://files.gitter.im/AtomLinter/Linter/T3X3/Screen-Shot-2015-06-20-at-00.15.23.png)

If you choose to collapse the panel you don't have a nice mechanism for jumping to the next error. Clicking the `x 2 errors` solves that.

**Comment by steelbrain** [comment]
Well. It isn't a difficult-to-implement feature anyway. But I agree that some legacy stuff sucks. So Yeah, let's do it.

**Comment by ababol** [comment]
Ok cool thanks! Here is a picture of how it looked like on the old linter.

![5e97443e-b3ac-11e4-9a4d-6bec8c269049](https://cloud.githubusercontent.com/assets/1850538/8264430/3e4ba100-16e6-11e5-825a-c048f9b8cb37.gif)
