### ISSUE TITLE
Support Linters Which Modify Buffers

### ISSUE THREAD

**Issue by joefitzgerald** [AtomLinter/linter-plus#78]
The implication of this suggestion is:

> Some linter providers must be run before others

For example: [`go-plus`](https://github.com/joefitzgerald/go-plus) includes three linters that modify the buffer:

* [`gofmt`](https://golang.org/cmd/gofmt/)
* [`goimports`](https://github.com/bradfitz/goimports)
* [`goreturns`](https://github.com/sqs/goreturns)

Each one is based on the functionality of the prior one, and a choice between them is mutually exclusive - i.e. you only run one of these on a buffer save event.

All other linters in go  (e.g. `golint`, `go vet`, `go build`, `go test`, etc.) must run after `gofmt` / `goimports` / `goreturns`. If `gofmt` / `goimports` / `goreturns` have a lint error, then all other linters should not be run, as these errors must be fixed.

If there were another linter which modified a buffer on save, that would need to be run serially (i.e. not in parallel). The linters which do not modify the buffer can be run in parallel.

All of the aforementioned linters need to be run using either `atom.BufferedProcess` or `child_process.spawnSync` as they are external processes.

The above is majority of what would be required to allow me to shift `go-plus` to use `linter-plus`.

> "But A Linter That Modifies The Buffer Isn't A Linter"
> _You might ask_

Sure it is. A buffer event (`save`) occurs. A tool is run. The tool either succeeds or fails. If it fails, show the warning(s) and / or error(s). If it succeeds, proceed. That the buffer is chanced if it succeeds is just a by-product of the linter's goal: to ensure consistent formatting of the source by _actually fixing the source_, so that being consistent is easy.

**Comment by steelbrain** [comment]
> All other linters in go  (e.g. `golint`, `go vet`, `go build`, `go test`, etc.) must run after `gofmt` / `goimports` / `goreturns`. If `gofmt` / `goimports` / `goreturns` have a lint error, then all other linters should not be run, as these errors must be fixed.

You will have to do this one in your package though, I mean, the latest API allows you to return multiple providers from package, so You create a var that's accessible in all their scopes and do some if/else love to check if `gofmt` / `goimports` / `goreturns` have errors and stop the other linters from running.

Also running the linter's in series is gonna cost a bit complexity, but Hey It's worth it :smiley:

**Comment by steelbrain** [comment]
From our slack conversation, Mr Joe suggested that we should have a `modifiesBuffer` flag with the providers and invoke those providers in series first, after they are all done, invoke normal providers in parallel.

**Comment by AsaAyers** [comment]
But how do you know what order to run them?

**Comment by joefitzgerald** [comment]
Order doesn't matter for my use case. Let's worry about order if / when it comes up as an issue.

**Comment by steelbrain** [comment]
Note to self: Use the method in [this answer][1] to execute buffer modifying linters in sequence, and at the end, trigger the normal linters.

[1]:http://stackoverflow.com/a/20105079/2652018

**Comment by steelbrain** [comment]
Move to https://github.com/AtomLinter/Linter/issues/696
