### ISSUE TITLE
Create README for users

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-plus#79]
The current README is very focused on `linter-*` developers. Since this is what users will see on apm I think we should change the top to be more like the existing Linter's README. Possibly copying large portions of it.

@steelbrain Are you able to make a new video to replace the one that's there?

**Comment by k2b6s9j** [comment]
Copying the top I'm down with. But let's leave the directory of available linters to the website I've created.

**Comment by AsaAyers** [comment]
As long as it's 100% ready by launch time early next week and the readme links to it, I'm fine with that plan. If it's not ready lets copy the README and replace it when it is ready.

**Comment by steelbrain** [comment]
I am :-1: on keeping a list of providers in README.md instead of a wiki page.

**Comment by k2b6s9j** [comment]
The website is ready. I'm waiting on @hd-deman to make it public.

**Comment by k2b6s9j** [comment]
@steelbrain The list of providers will not go in the readme, it will go on the website.

**Comment by AsaAyers** [comment]
The fact is that users will look at https://atom.io/packages/linter first. That's where the list needs to be

**Comment by steelbrain** [comment]
@AsaAyers how about a link to the website or wiki page instead of the whole list there.

**Comment by AsaAyers** [comment]
Users come first, above both of you and above me. There is no reason to make the user jump through hoops to go out and find the linters they need.

That might be an ok compromise as long as it's ready at launch time

**Comment by steelbrain** [comment]
@AsaAyers You have got to be absolutely kidding me, autocomplete+ links to the wiki page in the README and users visit that wiki page.

**Comment by k2b6s9j** [comment]
We could list the languages with linters available. As a user I would look at linter core I'd want an abstract of what the linters can handle. If I want a specific linter tool (like eslint vs jshint) I'd look for those directly.

**Comment by steelbrain** [comment]
https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers <-- @AsaAyers

**Comment by AsaAyers** [comment]
You've got to be absolutely kidding me! You're going to argue over every single thing?

> As long as it's 100% ready by launch time early next week and the readme links to it, I'm fine with that plan. 

Have it ready by launch and it's fine, if whatever you want to do isn't ready then just add the damn list to the README and be done with it. I don't really care what your solution is as long as users have easy access to it from the most natural place which is the APM page.

Seriously, I hate working with you more often than not. Why am I still here?

**Comment by k2b6s9j** [comment]
The website I've made divides all the linters by the languages/environments they support, so it is wholly possible to link to link to a JavaScript page from the readme on APM and see all the JavaScript linters available.

**Comment by steelbrain** [comment]
@AsaAyers I try my best not to argue over every single thing, I really do. But it's something that has better practices available, so being a friend I am gonna suggest you a better solution.

Atom is an IDE/Code Editor so it's user's are smart enough to click a link if they are looking for linter providers. Also we won't have to publish an apm update every time we add a new entry there, if we keep the list separate.

**Comment by AsaAyers** [comment]
> The fact is that users will look at https://atom.io/packages/linter first. That's where the list needs to be

I'll correct this statement. "The user needs to get to the list from there". I'm fine with linking to the list, as long as this mystery site or wiki is ready. Since you two are so opinionated on this I'm going to leave this issue up to you two to work out the details.

**Comment by steelbrain** [comment]
Closing as fixed.
