### ISSUE TITLE
Make error pane dismissable / minimizable

### ISSUE THREAD

**Issue by bolinfest** [AtomLinter/linter-plus#87]
Currently, we have files that may have so many lint warnings that the pane fills up to the point that the editor is unusably small. Rather than "punish" users who have a lot of lints to fix, they should be able to minimize the linter pane so they can actually see their code and fix them.

**Comment by k2b6s9j** [comment]
:+1:

**Comment by k2b6s9j** [comment]
This is something needed for nuclide to work well, might be needed for the release.

**Comment by steelbrain** [comment]
Dupe of #75

**Comment by steelbrain** [comment]
Double click the bottom tabs to hide the panel.

**Comment by tony-garcia** [comment]
I understand this package became the main Linter package. But in that one I can't hide the panel by double-clicking it. Did this change not make it into Linter?

**Comment by AsaAyers** [comment]
You used to be able to single click the active tab and it would collapse the panel. This appears to be broken now.

![selection_148](https://cloud.githubusercontent.com/assets/324999/8762739/a30087ee-2d4f-11e5-84d0-212bbd8628a7.png)
