### ISSUE TITLE
A ui to hide/minimize the Panel

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-plus#88]
Requirements
 - A minimize button when maximized
 - A maximize button when minimized

The badges, tooltips and other stuff stays unaffected, it's gonna be a panel only thing.
/cc @simurai (design suggestions?)

**Comment by steelbrain** [comment]
Fixes #87 #75

**Comment by Janther** [comment]
Also would love a comeback of the display errors of the selected line and only the selected line.

**Comment by steelbrain** [comment]
@Janther your message was confusing, please elaborate

**Comment by Janther** [comment]
The panel displays **all** the errors of the file and therefore it makes desirable a hide/minimize behaviour but if you only display the errors of the **selected line** (if it has an error) most of the time you won't have anything to display and will be "minimized".
And when you have the cursor on a highlighted line then the panel should display the errors of that specific.
Its like the inline tooltip but on the panel at the bottom.

**Comment by Janther** [comment]
The original linter package use to have this option and was very clean for me since I could focus on the errors of a specific line or method.

**Comment by steelbrain** [comment]
@Janther from what I've understood so far, You want to hide the panel and only see inline tooltips, that is exactly what I had planned.

**Comment by Janther** [comment]
No, I want to display a subset of the errors on the panel.
its a bit weird to have the tooltip block the view of the next line and on some line i have more than 1 error.
I would like to see only those errors on the panel at the bottom of the screen.

![screenshot 2015-06-23 12 20 55](https://cloud.githubusercontent.com/assets/1022054/8309734/66f816c4-19a2-11e5-96bf-c1288ec88019.png)

For example if the cursor is on line 2 I would rather see the first 2 errors than of all 5 of them, and when I move the cursor to line 3 the 3 errors from that line should be displayed.

In a perfect world if I make a selection of a bunch of lines the errors regarding those lines should appear on the panel

**Comment by Janther** [comment]
@steelbrain Did I get my point across?

**Comment by iam4x** [comment]
@Janther the old behaviour? statusbars issues are related on which row your cursor is?

**Comment by steelbrain** [comment]
@Janther, Yep, You were asking to have the errors near the cursor appear in panel, instead of all of them.

**Comment by iam4x** [comment]
@steelbrain You want to address yourself on this? Or you want some backup?

**Comment by steelbrain** [comment]
Talking about points in comment 1: Sure
Talking about this old behaviour: Not sure, might want to discuss on slack first

**Comment by Janther** [comment]
@iam4x exactly, I don't know if the behaviour was taken for simplicity.
but it really worked for me plus it takes care on the long panel issue.

**Comment by steelbrain** [comment]
@Janther you might want to have a look the discussion that happened at https://github.com/AtomLinter/Linter/issues/587

**Comment by steelbrain** [comment]
Double click the bottom tabs to hide the panel.
